<?php
require_once '../DataStore.php';
require_once 'testDB_functions.php';
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-11-04 at 11:23:53.
 */
class DataStoreTest extends PHPUnit_Framework_TestCase
{
   /**
    * @var DataStore
    */
   protected $object;
   /**
    * @var PDO
    */
   protected $pdo;

   /**
    * Sets up the fixture, for example, opens a network connection.
    * This method is called before a test is executed.
    */
   protected function setUp()
   {
      $this->object = new DataStore;
      
      if($this->pdo == null)
      {
         $this->pdo = testDB_functions::getConnection();
      }
   }

   /**
    * Tears down the fixture, for example, closes a network connection.
    * This method is called after a test is executed.
    */
   protected function tearDown()
   {
      testDB_functions::resetDB($this->pdo);
   }
   
   /**
    * @covers DataStore::__construct
    */
   public function testDidIBuild()
   {
      $this->assertTrue($this->object->getId() != NULL);
   }
   
   /**
    * @covers Process::save
    */
   public function testSave_smoke()
   {
      
      $this->object->setLabel('name');
      $this->object->setOriginator('Josh');
      $this->object->setLocation(50, 60);
      $this->object->save($this->pdo);

      $row = $this->pdo->query("SELECT * FROM entity WHERE id = '".$this->object->getId()."'")->fetch();
      $this->assertEquals($this->object->getId(), $row['id'] );
      $this->assertEquals($this->object->getLabel(), $row['label'] );
      $this->assertEquals($this->object->getOriginator(), $row['originator'] );
      $this->assertEquals(Constants::DataStore, $row['type'] );
      
      $row = $this->pdo->query("SELECT * FROM element WHERE id = '".$this->object->getId()."'")->fetch();
      $this->assertEquals($this->object->getX(), $row['x'] );
      $this->assertEquals($this->object->getY(), $row['y'] );
   }

}
