<?php
require_once '../Process.php';
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-11-04 at 11:16:29.
 */
class ProcessTest extends PHPUnit_Framework_TestCase
{
   /**
    * @var Process
    */
   protected $object;

   /**
    * Sets up the fixture, for example, opens a network connection.
    * This method is called before a test is executed.
    */
   protected function setUp()
   {
      $this->object = new Process;
   }

   /**
    * Tears down the fixture, for example, closes a network connection.
    * This method is called after a test is executed.
    */
   protected function tearDown()
   {
      
   }
   
   /**
    * @covers Process::__construct
    */
   public function testDidIBuild()
   {
      $this->assertTrue($this->object->getId() != NULL);
   }
   
   /**
    * @covers Process::save
    */
   public function testSave()
   {
      $pdo = $this->getConnection();
      $this->object->setLabel('name');
      $this->object->setOriginator('Josh');
      $this->object->setLocation(50, 50);
      $this->object->save($pdo);
      $this->resetDB($pdo);
   }
   
   /**
    * 
    * @return PDO
    */
   public function getConnection()
   {
      $db_hostname = 'localhost';
      $db_database = 'dedc';
      $db_username = 'tester';
      $db_password = 'test';

      // Combined driver/host/db string
      // Comment and uncomment the relevant ones for your prefered RDMS
      $db_id = "mysql:host=$db_hostname;dbname=$db_database";
      //$db_id = "pgsql:host=$db_hostname;dbname=$db_database";

      // DB Setup
      $dbh;
      try 
      {
          $dbh = new PDO($db_id, $db_username, $db_password);
      }
      catch (PDOException $e)
      {
          die("Failed to connect to DB" . $e->getMessage());
      }
      $dbh->setAttribute( PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION );
      return $dbh;
   }
   
   public function resetDB($pdo)
   {
      if( $pdo instanceof PDO)
      {
         $pdo->query('USE dedc;');
         $pdo->query('SET foreign_key_checks=0;');
         $pdo->query('TRUNCATE TABLE entity;');
         $pdo->query('TRUNCATE TABLE element;');
         $pdo->query('TRUNCATE TABLE dataflow;');
         $pdo->query('TRUNCATE TABLE external_links;');
         $pdo->query('TRUNCATE TABLE element_list;');
         $pdo->query('TRUNCATE TABLE multiprocess;');
         $pdo->query('SET foreign_key_checks=1;');
      }
      else 
      {
         throw new BadFunctionCallException("input parameter was not a PDO");
      }
   }

}
