<?php

require_once '../Process.php';
require_once '../DataFlow.php';
require_once 'testDB_functions.php';

require_once 'Storage/DatabaseStorage.php';

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-11-04 at 11:16:29.
 */
class ProcessTest extends PHPUnit_Framework_TestCase
{

    /**
     * @var Process
     */
    protected $object;

    /**
     * @var PDO
     */
    protected $pdo;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Process;

        if ($this->pdo == null)
        {
            $this->pdo = testDB_functions::getConnection();
        }
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        testDB_functions::resetDB($this->pdo);
    }

    /**
     * @covers Process::__construct
     */
    public function testDidIBuild()
    {
        $this->assertTrue($this->object->getId() != NULL);
    }

    /**
     * @covers Process::save
     */
    public function testSave_smoke()
    {
        $storage = new DatabaseStorage();
        $this->object->setLabel('name');
        $this->object->setOriginator('Josh');
        $this->object->setLocation(50, 60);

        $df1 = new DataFlow;
        $df1->setDestinationNode($this->object);
        $df1->save($this->pdo);

        $df2 = new DataFlow;
        $df2->setOriginNode($this->object);
        $df2->save($this->pdo);

        $this->object->save($storage);

        $row = $this->pdo->query("SELECT * FROM entity WHERE id = '" . $this->object->getId() . "'")->fetch();
        $this->assertEquals($this->object->getId(), $row['id']);
        $this->assertEquals($this->object->getLabel(), $row['label']);
        $this->assertEquals($this->object->getOriginator(), $row['originator']);
        $this->assertEquals(Types::Process, $row['type']);

        $row = $this->pdo->query("SELECT * FROM element WHERE id = '" . $this->object->getId() . "'")->fetch();
        $this->assertEquals($this->object->getX(), $row['x']);
        $this->assertEquals($this->object->getY(), $row['y']);

        $rows = $this->pdo->query("SELECT * FROM node WHERE id = '" . $this->object->getId() . "'");
        for ($i = 0; $i < $this->object->getNumberOfLinks(); $i++)
        {
            $row = $rows->fetch();
            $this->assertEquals($this->object->getLinkbyPosition($i)->getId(), $row['df_id']);
        }
    }

}
