<?php
require_once '../Process.php';
require_once 'testDB_functions.php';
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-11-04 at 11:16:29.
 */
class ProcessTest extends PHPUnit_Framework_TestCase
{
   /**
    * @var Process
    */
   protected $object;
   
   /**
    * @var PDO
    */
   protected $pdo;

   /**
    * Sets up the fixture, for example, opens a network connection.
    * This method is called before a test is executed.
    */
   protected function setUp()
   {
      $this->object = new Process;
   }

   /**
    * Tears down the fixture, for example, closes a network connection.
    * This method is called after a test is executed.
    */
   protected function tearDown()
   {
      
   }
   
   /**
    * @covers Process::__construct
    */
   public function testDidIBuild()
   {
      $this->assertTrue($this->object->getId() != NULL);
   }
   
   /**
    * @covers Process::save
    */
   public function testSave()
   {
      $this->pdo = testDB_functions::getConnection();
      testDB_functions::resetDB($this->pdo);
      $this->object->setLabel('name');
      $this->object->setOriginator('Josh');
      $this->object->setLocation(50, 50);
      $this->object->save($this->pdo);
      testDB_functions::resetDB($this->pdo);
   }

}
