<?php
require_once "../../Request/SimpleRequest.php";

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-01-11 at 17:30:58.
 */
class SimpleRequestTest extends PHPUnit_Framework_TestCase
{

    /**
     * @var simpleRequest
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        //$this->object = new SimpleRequest;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * Checks that the processHeader function successfully gets out the
     * accept header for a single media type
     * 
     * @covers simpleRequest::processHeader
     */
    public function testSingleMediaType()
    {
        $testType = "text/html";
        $header = array(
            'Accept' => $testType
            );
        $singleMedia = new SimpleRequest($header);
        $result = $singleMedia->getAccept();
        $this->assertEquals($testType, $result[0]);
    }
    
    public function testMultipleMediaType()
    {
        $testTypes = array("text/html", "text/xml", "text/json");
        $header = array(
            'Accept' => implode(", ", $testTypes)
        );
        $multiMedia = new SimpleRequest($header);
        $result = $multiMedia->getAccept();
        
        // First ensure that the same number of results are returned
        // as there were inputs
        $this->assertEquals(count($result), count($testTypes));
        // Then check they match
        for ($i = 0; $i < count($result); $i++)
        {
            $this->assertEquals($testTypes[$i], $result[$i]);
        }
    }
}
