<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-03-20 at 22:15:02.
 */
class PasswordAuthenticationTest extends PHPUnit_Framework_TestCase
{

    /**
     * @var PasswordAuthentication
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new PasswordAuthentication;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers PasswordAuthentication::getAuthenticationMethod
     * @todo   Implement testGetAuthenticationMethod().
     */
    public function testGetAuthenticationMethod()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
