<?php
require_once "../Admin.php";
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-11-03 at 20:39:45.
 */
class AdminTest extends PHPUnit_Framework_TestCase
{

    /**
     * @var Admin
     */
    protected $admin;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->admin = new Admin("TestAdmin", "TestOrg");
    }


    /**
     * @covers Admin::isAdmin
     * Makes sure that isAdmin returns false.
     */
    public function testIsAdmin()
    {
        $this->assertTrue($this->admin->isAdmin());
    }

}
