<?php

require_once 'User.php';
require_once '../DatabaseStorage.php';
require_once 'AuthenticationInformation/PasswordAuthentication.php';

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-03-21 at 21:33:52.
 */
class UserTest extends PHPUnit_Framework_TestCase 
{
    
    private $storage;
    
    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->storage = new DatabaseStorage();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }
    
    /**
     * 
     * @param type $org
     * @param type $name
     * @param type $password
     * @dataProvider credProvider
     */
    private function testUserCreationByAuthInfo($org, $name, $password)
    {
        $authInfo = new PasswordAuthentication($org . "/" . $name, $password);
        $user = new User($this->storage, $authInfo);
        
        $this->assertEquals($org, $user->getOrganization());
        $this->assertEquals($name, $user->getUserName());
    }

    
    protected function credProvider()
    {
        return array(
            array("InD", "Geoff", "NotSuperSecret"),
        );
 
    }
}
