<?php
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-11-04 at 10:47:16.
 */
class DataFlowTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var DataFlow
     */
    protected $object;

    /**
     *
     * @var DatabaseStorage
     */
    protected $storage;
    /**
     *
     * @var DataFlowDiagram
     */
    protected $testDiagram;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        if ($this->storage == null)
        {
            $this->storage = new DatabaseStorage();
        }
        
        $this->testDiagram = new DataFlowDiagram($this->storage);
        $this->object = new DataFlow($this->storage, $this->testDiagram->getId());
        $this->testDiagram->refresh();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        //clear the DB
        $this->testDiagram->refresh();
        $this->testDiagram->delete();
    }
    
    /**
     * @covers DataStore::__construct
     */
    public function testDidIBuild()
    {
        $this->assertTrue($this->object->getId() != NULL);
    }

}
